name: Release Builds

on:
  release:
    types: [ created ]

jobs:
  build:
    strategy:
      matrix:
        build_type: [ ubuntu, macos, windows ]
        gui: [ gui, cli ]
    runs-on: ${{ matrix.build_type }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true

      - name: Install Node modules
        run: |
          npm install

      - name: Get name and version from package.json
        run: |
          test -n $(node -p -e "require('./package.json').name") &&
          test -n $(node -p -e "require('./package.json').version") &&
          echo PACKAGE_NAME=$(node -p -e "require('./package.json').name") >> $GITHUB_ENV &&
          echo PACKAGE_VERSION=$(node -p -e "require('./package.json').version") >> $GITHUB_ENV || exit 1
      - name: Make build
        run: npm run build-${{ matrix.build_type }}-${{ matrix.gui }}

      - name: Upload release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: multi-downloader-nx-${{ matrix.build_type }}-${{ matrix.gui }}.7z
          asset_path: ./lib/_builds/multi-downloader-nx-${{ matrix.build_type }}64-${{ matrix.gui }}.7z
          asset_content_type: application/x-7z-compressed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
